POST http://localhost:1006/curve HTTP/1.1
content-type: application/json

{
    "type": "superAdditiveCurve",
    "baseSequence": 
    {
        "elements": [
            {
                "type":"point",
                "time":0,
                "value":0
            },
            {
                "type":"segment",
                "startTime":0,
                "endTime":10,
                "rightLimitAtStartTime":0,
                "slope":0
            },
            {
                "type":"point",
                "time":10,
                "value":0
            },
            {
                "type":"segment",
                "startTime":10,
                "endTime":11,
                "rightLimitAtStartTime":0,
                "slope":20
            }
        ]
    },
    "pseudoPeriodStart":10,
    "pseudoPeriodLength":1,
    "pseudoPeriodHeight":20
}
